refactor of SNIP_R and Slurm Error handling

diff --git a/bin/hty b/bin/hty
--- a/bin/hty
+++ b/bin/hty
@@ -501,10 +501,53 @@ buildjob() {
   #local RET; local RES; local NODES
   #local PARTS; local WTIMES; local DEFPART
   #local RCORES; local RMEM; local RTIME
-  unset SBATCHHEAD RCORES RMEM RTIME RPART 
+  unset SBATCHHEAD RCORES RMEM RTIME RPART
+
+  SBATCH=''
+  SEMAIL='name@org.edu'
+  if htyInPath git; then
+    SEMAIL=$(git config --global user.email)
+  fi
+
+  if ! htyInPath "sacctmgr"; then
+
+QST=$(cat << EOF
+Slurm does not seem to be installed on this
+System (could not find sacctmgr). 
+Please try again on a system that has Slurm
+installed.
+EOF
+)
+    dialog --title "Slurm not found!" \
+             --backtitle "HPC Toys" \
+             --msgbox "${QST}" 0 0
+    exit 1
+
+#    SBATCH+="#SBATCH --job-name=MyJob\n"
+#    SBATCH+="#SBATCH --nodes=1 --ntasks=1\n"
+#    SBATCH+="#SBATCH --cpus-per-task=1\n"
+#    SBATCH+="#SBATCH --mem-per-cpu=1G\n"
+#    SBATCH+="#SBATCH --time=1-00:00:00\n"
+#    SBATCH+="#SBATCH --output=MyJob_%A_%a.out\n"
+#    SBATCH+="#SBATCH --error=MyJob_%A_%a.err\n"
+#    SBATCH+="#SBATCH --array=1-1%1                 # %13 = run 13 jobs in parallel\n"
+#    SBATCH+="#SBATCH --mail-type=FAIL,END          # or NONE/ALL or BEGIN,FAIL,END\n"
+#    SBATCH+="#SBATCH --mail-user=${SEMAIL}\n"
+#    SBATCH=${SBATCH::-2} # strip final new line
+#    return 0
+  fi
+
+  #htyEcho $SBATCH 0
 
   # get partitions with configs from Slurm
   ALLPARTS=$(scontrol show partition --oneliner)
+
+  MYRET=$?
+  if [[ ${MYRET} -gt 0 ]]; then  
+    htyEcho "Slurm returned error ${MYRET}" 
+    htyEcho "Please run this tool on a functioning HPC system" 0
+    exit 1
+  fi
 
   # get my account and QOS info from Slurm
   MYACCQOS=$(sacctmgr --noheader show associations \
@@ -556,9 +599,9 @@ buildjob() {
     #echo "MY ALLOWED PARTITIONS: ${MYPARTS}"
   fi
 
-  #htyEcho "PTMAXTIME: ${PTMAXTIME[${RPART}]}, RPART: ${RPART}" 0
-
   slurmGetNodeInfo "${RPART}"  
+
+  #htyEcho "PTMAXTIME: ${PTMAXTIME[${RPART}]}, RPART: ${RPART}" 0
 
 QST=$(cat << EOF
 How many CPU cores are you requesting per node or
@@ -967,7 +1010,7 @@ like to run with your script. You can check files
 or simply choose "- all files -" to include all
 files in that folder.
 Selected filenames will be saved to a list called
-${MYJOBARR}.filelist.txt 
+filelists/${MYJOBARR}.filelist.txt 
 EOF
 )
 
@@ -1025,14 +1068,15 @@ EOF
                    && FLDEND='yes'
   done
   # write MYDATA array to file
-  FILELISTTXT="${REPOSFLD}/${MYJOBARR}.filelist.txt"
+  mkdir -p "${REPOSFLD}/filelists"
+  FILELISTTXT="${REPOSFLD}/filelists/${MYJOBARR}.filelist.txt"
   printf "%s\n" "${MYDATA[@]}" > "${FILELISTTXT}"
 
   # in addition create symlinks for each array
-  mkdir -p "${REPOSFLD}/${MYJOBARR}.filelist"
+  mkdir -p "${REPOSFLD}/filelists/${MYJOBARR}.filelist"
   for F in "${MYDATA[@]}"; do 
     B=$(basename "${F}")
-    ln -s "${F}" "${REPOSFLD}/${MYJOBARR}.filelist/${B}"
+    ln -s "${F}" "${REPOSFLD}/filelists/${MYJOBARR}.filelist/${B}"
   done
   
 # Now building a job and adding a few special Array job options
@@ -1189,14 +1233,16 @@ EOF
 
   #cat "${CODEPATH}"
 
+  
+
   htyEcho "\nTo test the first array job you can simply run:"
-  htyEcho "\"${CODEPATH}\" \"${REPOSFLD}/${MYJOBARR}.filelist.txt\""
+  htyEcho "\"${CODEPATH}\" \"${REPOSFLD}/filelists/${MYJOBARR}.filelist.txt\""
       
   htyEcho "\nTo execute the entire job array execute this command:"
-  htyEcho "sbatch \"${CODEPATH}\" \"${REPOSFLD}/${MYJOBARR}.filelist.txt\""
+  htyEcho "sbatch \"${CODEPATH}\" \"${REPOSFLD}/filelists/${MYJOBARR}.filelist.txt\""
 
   htyEcho "\nOr you run the submit script to execute the entire job array"
-  htyEcho "sbatch \"${MYSUB}\""
+  htyEcho "sbatch \"${MYSUB}\"" 0
 
 }
 
@@ -1267,34 +1313,56 @@ EOF
 # the Nth line of  *.filelist.txt where
 # N = SLURM_ARRAY_TASK_ID = tid
 #
-args <- commandArgs(TRUE)
-if (length(args) == 0) {
-  stop("enter a file name of a pointers file as last argument")
+def getDataFiles <- function() {
+    args <- commandArgs(TRUE)
+    datafiles <- character()  #initialize a str vector
+    if (length(args) == 0) {
+        return(datafiles)
+    }
+    tid <- Sys.getenv(c("SLURM_ARRAY_TASK_ID"))
+    if (tid == '') {tid <- "1"}
+    # we do NOT store task id as first element 
+    # because R lists are not zero based 
+    for (i in 1:length(args)){
+        argfile = args[i]
+        if (!file.exists(argfile)) {
+            next
+        }
+        if (!endsWith(argfile, ".filelist.txt")){
+            append(datafiles, argfile)
+            next
+        }
+        fh <- file(argfile, "r")
+        filelist = <- readLines(fh)
+        close(fh)
+        if (length(filelist) < strtoi(tid)) {
+          cat("Task ID larger than number of data files")
+          next
+        }
+        datafile=filelist[strtoi(tid)]
+        if (!file.exists(datafile)) {
+            cat("Data file does not exist.")
+            next
+        }
+        append(datafiles,datafile)
+    }
+    return(datafiles)
 }
-ptsfile <- tail(args, n=1)
-if (!file.exists(ptsfile)) {
-  stop(sprintf("Pointers file %s does not exist.", ptsfile))
-}
-fh <- file(ptsfile, "r")
-tid <- Sys.getenv(c("SLURM_ARRAY_TASK_ID"))
-if (tid == '') {tid <- "1"}
-dtfiles <- readLines(fh)
-if (length(dtfiles) < strtoi(tid)) {
-  stop("Task ID larger than number of data files")
-}
-dtfile <- dtfiles[strtoi(tid)]
-close(fh)
-cat ("Data File: ", dtfile,'\n')
-fh <- file(dtfile, "r")
-lines <-readLines(fh)
-close(fh)
-cat ("Read 1st 3 lines:\n")
-for (i in 1:length(lines)){
-  cat(lines[i],'\n')
-  if (i >= 3) {
-    break
-  }
-}
+
+# using the datafiles list in your code
+datafiles <- getDataFiles()
+if (length(datafiles) > 0) {
+    # start reading with index=1
+    #tid <- Sys.getenv(c("SLURM_ARRAY_TASK_ID"))
+    for (i in 1:length(datafiles)){
+        cat (" *** R TASK: 1st 3 lines of ", datafiles[i])
+        j <- 0
+        fh <- file(argfile, "r")
+        for(j in 1:3) {
+            line <- scan(file=fh, nlines=1, quiet=TRUE)
+        }
+        close(fh)      
+    }
 ##### End HPC Toys ##########
 EOF
 )
